### ISSUE TITLE
[Module] Player/Comments

### ISSUE THREAD

**Issue by katopz** [digithun/clogii-mobile#12]
# Raw
- https://github.com/graphcool-examples/react-native-apollo-instagram-subscriptions-example/tree/8eb874a1603641e0536729da68badc4a014ac36a

# Expect
- [x] ~~Can navigate to player~~  => [Module] Player/Comments_Navigator #63
- [x] Can comment clog (Text /  Emoji)
- [x] ~~User can edit/delete on their own~~  => [Module] Player/Comments_edit/delete #64
- [x] Comment time stamp
- [x] ~~Can love comment~~ => [Module] Player/Comments_emotion #65

### view
![comment_1](https://cloud.githubusercontent.com/assets/24914167/22099867/aa450864-de5f-11e6-861e-9fb7066dff36.jpg)
