### ISSUE TITLE
[Module] Authenications/Email

### ISSUE THREAD

**Issue by katopz** [digithun/clogii-mobile#17]
## How to
- http://blog.parse.com/2012/05/07/express-your-brand-with-parse/
- http://blog.mailgun.com/parse-partners-with-mailgun-for-simple-integration/

## Source
- https://github.com/ParsePlatform/parse-server/tree/master/public_html
- https://github.com/ParsePlatform/parse-server-simple-mailgun-adapter/blob/master/index.js
- https://github.com/ParsePlatform/ParseReact/blob/master/demos/AnyBudget/js/LoginWrapper.react.js

## Tasks
- [x] User can signup with email.
- [x] User get confirm by email via MailGun.
- [x] User can login with email.
- [x] User can recover forget password  via MailGun.
- [x] User can navigator back from Login Screen
- [x] Add login with email button, inside playing app.
