### ISSUE TITLE
[Mobile] Tracking app events

### ISSUE THREAD

**Issue by katopz** [digithun/clogii-mobile#42]
Maybe with Google Analytic or Firebase.
- [ ] App events get track by tags e.g. LOG, DEBUG, INFO, WARN, ERROR.
- [ ] Can change tag for target devices remotely.
- [ ] Admin can see app events and logs.
